package comment;

import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Date;
import java.util.List;

import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import album.info.AlbumDAO;
import album.info.AlbumVO;

@WebServlet("/artistcomment")
public class CommentServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doHandle(request, response);
	}

	protected void doPost(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		doHandle(request, response);
	}
	
	protected void doHandle(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		request.setCharacterEncoding("utf-8");
		response.setContentType("text/html; charset=utf-8;");
		PrintWriter out = response.getWriter();
		
		out.write("\r\n");
	      out.write("<!DOCTYPE html>\r\n");
	      out.write("<html>\r\n");
	      out.write("<head>\r\n");
	      out.write("<meta charset=\"UTF-8\">\r\n");
	      out.write("<title>Artist.jsp Test전용</title>\r\n");
	 		CommentDAO dao = new CommentDAO();

			String command = request.getParameter("command"); 
			
			if("addcomment".equals(command)) {
				String id_1 = request.getParameter("id");
				String cont_1 = request.getParameter("cont");
				
				CommentVO vo = new CommentVO();
				vo.setComment_id(id_1);
				vo.setComment_cont(cont_1);
				
				dao.addcomment(vo);
			}else if("delcommnet".equals(command)) {
				
				String id_2 = request.getParameter("id");
				System.out.println("delete 확인"+id_2);
				dao.delcomment(id_2);
			}
			
			List<CommentVO> list = dao.listComment();
	      out.write("\r\n");
	      out.write(" <script>\r\n");
	      out.write(" 		/*댓글 입력창 if문*/\r\n");
	      out.write("        function fn_sendComment(){\r\n");
	      out.write("        	\r\n");
	      out.write("        	var frmCommand = document.frmComment;\r\n");
	      out.write("        	var id = frmCommand.id.value;\r\n");
	      out.write("        	var cont = frmCommand.cont.value;\r\n");
	      out.write("        	\r\n");
	      out.write("        	if(id.length == 0 || id == \"\"){\r\n");
	      out.write("        		alert(\"아이디를 입력해주세요\")\r\n");
	      out.write("        	}else if(cont.length == 0 || cont == \"\"){\r\n");
	      out.write("        		alert(\"내용을 입력해주세요\")\r\n");
	      out.write("        	}else{\r\n");
	      out.write("            frmComment.method = \"post\";\r\n");
	      out.write("            frmComment.action = \"artistcomment\";\r\n");
	      out.write("            frmComment.submit();\r\n");
	      out.write("        	}\r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("        var prevScrollpos = window.pageYOffset;\r\n");
	      out.write("        window.onscroll = headerbarToggle\r\n");
	      out.write("        window.onload = headerbarToggle\r\n");
	      out.write("        function headerbarToggle(){\r\n");
	      out.write("            console.log(1234);\r\n");
	      out.write("        /*메뉴상단 스크롤 함수*/\r\n");
	      out.write("            var headerbar = document.getElementById(\"menu\");\r\n");
	      out.write("            var currentScrollPos = window.pageYOffset;\r\n");
	      out.write("            if(prevScrollpos < currentScrollPos){\r\n");
	      out.write("                headerbar.style.opacity = 1;\r\n");
	      out.write("            }else{\r\n");
	      out.write("                headerbar.style.opacity = 0.6;\r\n");
	      out.write("            }\r\n");
	      out.write("            \r\n");
	      out.write("            /*앨범 < > 함수*/\r\n");
	      out.write("            let prev = document.querySelector(\".prev\");\r\n");
	      out.write("            let next = document.querySelector(\".next\");\r\n");
	      out.write("            let slides = document.querySelector(\".clides\");\r\n");
	      out.write("            let slds = document.querySelector(\"#slds\");\r\n");
	      out.write("            let slidelmg = document.querySelectorAll(\".clides li\");\r\n");
	      out.write("            let current = 0;\r\n");
	      out.write("            let slideCount = slidelmg.length;\r\n");
	      out.write("\r\n");
	      out.write("    	       next.addEventListener('click', function() {\r\n");
	      out.write("    	           console.log(slideCount); /*5*/\r\n");
	      out.write("    	           if(current !== slideCount){\r\n");
	      out.write("    	           		console.log('안녕 친구들');\r\n");
	      out.write("    	        	    current = slideCount;\r\n");
	      out.write("    	        	    console.log(current);\r\n");
	      out.write("    	           		slds.classList.add(\"marLeft\");\r\n");
	      out.write("    	           }\r\n");
	      out.write("    	       });\r\n");
	      out.write("    	        \r\n");
	      out.write("    	       prev.addEventListener('click', function() {\r\n");
	      out.write("    	    	   if(current !== 0){\r\n");
	      out.write("    	           	console.log('hello');\r\n");
	      out.write("    	           	console.log(slideCount);\r\n");
	      out.write("    	           	slds.classList.remove(\"marLeft\");\r\n");
	      out.write("    	           	current = 0;\r\n");
	      out.write("    	    	   }\r\n");
	      out.write("    	       });\r\n");
	      out.write("    	       \r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("  </script>\r\n");
	      out.write("  <style>\r\n");
	      out.write("  \r\n");
	      out.write("  		/*공통으로 적용 될거*/\r\n");
	      out.write("        body{\r\n");
	      out.write("            background-color: black;\r\n");
	      out.write("            margin: 0;\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        div{\r\n");
	      out.write("            /* border: 1px solid white; */\r\n");
	      out.write("            color : white;\r\n");
	      out.write("            /* vertical-align: middle; */\r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("        img{\r\n");
	      out.write("        	border-radius: 12px;\r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("        a{\r\n");
	      out.write("            text-decoration: none;\r\n");
	      out.write("            color: white;\r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("        /*메뉴 상단바*/\r\n");
	      out.write("        header{\r\n");
	      out.write("            background-color: black;\r\n");
	      out.write("            color: white;\r\n");
	      out.write("            width: 100%;\r\n");
	      out.write("            position:fixed;\r\n");
	      out.write("            height: 53px;\r\n");
	      out.write("            border-bottom:1px solid rgb(70, 70, 70);\r\n");
	      out.write("            z-index: 1;\r\n");
	      out.write("            transition: opacity 0.4s;\r\n");
	      out.write("        }\r\n");
	      out.write("		\r\n");
	      out.write("        /*홈, 인기차트, 보관함, 검색창 있는 div박스*/\r\n");
	      out.write("        #menu{\r\n");
	      out.write("            margin: 0;\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .menu-box{\r\n");
	      out.write("            display: inline-block;\r\n");
	      out.write("            position:absolute;\r\n");
	      out.write("            left: 50%;\r\n");
	      out.write("            top: 10px;\r\n");
	      out.write("        }\r\n");
	      out.write("		.main{\r\n");
	      out.write("            color: rgb(159, 159, 159);\r\n");
	      out.write("			font-size: 20px; \r\n");
	      out.write("            font-weight: 600;\r\n");
	      out.write("            margin: 0px 13px;\r\n");
	      out.write("		}\r\n");
	      out.write("\r\n");
	      out.write("        .main_1:hover{\r\n");
	      out.write("            color: white;\r\n");
	      out.write("            cursor: pointer;\r\n");
	      out.write("        }\r\n");
	      out.write("        .main_2:hover{\r\n");
	      out.write("            color: white;\r\n");
	      out.write("            cursor: pointer;\r\n");
	      out.write("        }\r\n");
	      out.write("        .main_3:hover{\r\n");
	      out.write("            color: white;\r\n");
	      out.write("            cursor: pointer;\r\n");
	      out.write("        }\r\n");
	      out.write("        .main_4:hover{\r\n");
	      out.write("            color: white;\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .main-box{\r\n");
	      out.write("            display: inline-block;\r\n");
	      out.write("            height: 32px;\r\n");
	      out.write("            width:260px;\r\n");
	      out.write("            border: 1px solid rgb(98, 98, 98);\r\n");
	      out.write("            background-color: transparent;\r\n");
	      out.write("        }\r\n");
	      out.write("        .main-box:hover{\r\n");
	      out.write("            border: 1px solid rgb(176, 176, 176);\r\n");
	      out.write("        }\r\n");
	      out.write("        /*검색 입력창*/\r\n");
	      out.write("        .search-txt::placeholder{\r\n");
	      out.write("            font-size: 18px;\r\n");
	      out.write("            font-weight: 600;\r\n");
	      out.write("        }\r\n");
	      out.write("        .search-txt::placeholder:hover{\r\n");
	      out.write("            color:rgb(172, 172, 172);\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .search-txt{\r\n");
	      out.write("            width: 190px;\r\n");
	      out.write("            padding: 10px;\r\n");
	      out.write("            border: 0px;\r\n");
	      out.write("            outline:none;\r\n");
	      out.write("            background-color: transparent;\r\n");
	      out.write("            color: white;\r\n");
	      out.write("            \r\n");
	      out.write("        }\r\n");
	      out.write("        /*검색 버튼*/\r\n");
	      out.write("        .search-btn{\r\n");
	      out.write("            border : 0px;\r\n");
	      out.write("            width: 44px;\r\n");
	      out.write("            height: 100%;\r\n");
	      out.write("            float:right;\r\n");
	      out.write("            outline:none;\r\n");
	      out.write("            background-color: rgb(45, 45, 45);\r\n");
	      out.write("            color: rgb(159, 159, 159);\r\n");
	      out.write("            cursor: pointer;\r\n");
	      out.write("            font-weight: 600;\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .search-btn:hover{\r\n");
	      out.write("            color: rgb(206, 206, 206);\r\n");
	      out.write("            background-color: rgb(91, 91, 91);\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        /*프로필사진*/\r\n");
	      out.write("        .menu-img{\r\n");
	      out.write("            width: 38px;\r\n");
	      out.write("            float: right;\r\n");
	      out.write("            border-radius: 70%;\r\n");
	      out.write("            margin: 6px 14px;\r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("        #cont{\r\n");
	      out.write("            background-image:\r\n");
	      out.write("            linear-gradient(\r\n");
	      out.write("                to bottom,\r\n");
	      out.write("                rgba(0, 0, 0, 0) 10%,\r\n");
	      out.write("                rgba(0, 0, 0, 0.25) 25%,\r\n");
	      out.write("                rgba(0, 0, 0, 0.5) 50%,\r\n");
	      out.write("                rgba(0, 0, 0, 0.75) 75%,\r\n");
	      out.write("                rgb(0, 0, 0) 100%\r\n");
	      out.write("            ),\r\n");
	      out.write("            url(\"https://i.pinimg.com/1200x/08/81/34/088134b9c3c6d6a1fa2c037bae1d5b49.jpg\") ;\r\n");
	      out.write("            background-repeat: no-repeat;\r\n");
	      out.write("            background-size: cover;\r\n");
	      out.write("            background-position: center;\r\n");
	      out.write("            height: 550px;     \r\n");
	      out.write("            position: relative;\r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("        .text1{\r\n");
	      out.write("            color : white;\r\n");
	      out.write("            padding: 0px 10px;\r\n");
	      out.write("            position : absolute;\r\n");
	      out.write("            bottom : 0;\r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("        /* 노래목록 style */\r\n");
	      out.write("        #cont1{\r\n");
	      out.write("            display : flex;\r\n");
	      out.write("            justify-content: center;\r\n");
	      out.write("            height: 80px;\r\n");
	      out.write("        }\r\n");
	      out.write("        .box1{\r\n");
	      out.write("            width: 170px;\r\n");
	      out.write("            height: 60px;\r\n");
	      out.write("            margin: 0 15px;\r\n");
	      out.write("            text-align: left;     \r\n");
	      out.write("\r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("        hr{\r\n");
	      out.write("            width: 62%;\r\n");
	      out.write("            border: 0;\r\n");
	      out.write("            border-top: 1px solid rgb(98, 98, 98);\r\n");
	      out.write("        }\r\n");
	      out.write("        .img1{\r\n");
	      out.write("            width: 60px;\r\n");
	      out.write("        }\r\n");
	      out.write("		\r\n");
	      out.write("		/* 댓글 style*/\r\n");
	      out.write("        .comment{\r\n");
	      out.write("            display: flex;\r\n");
	      out.write("            justify-content: center;\r\n");
	      out.write("        }\r\n");
	      out.write("        .text2{\r\n");
	      out.write("            padding-top: 20px;\r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("		/*textarea input 스타일*/\r\n");
	      out.write("        textarea{\r\n");
	      out.write("            width: 500px;\r\n");
	      out.write("            height: 110px;\r\n");
	      out.write("            padding: 10px;\r\n");
	      out.write("            margin: 11px;\r\n");
	      out.write("            box-sizing: border-box;\r\n");
	      out.write("            border-radius: 15px;\r\n");
	      out.write("            color: white;\r\n");
	      out.write("            border: none;\r\n");
	      out.write("            resize: none;\r\n");
	      out.write("            background-color: rgb(70, 70, 70);\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .input1{\r\n");
	      out.write("            background-color: rgb(70, 70, 70);\r\n");
	      out.write("            color: white;\r\n");
	      out.write("            border-radius: 15px;\r\n");
	      out.write("            border: none;\r\n");
	      out.write("            height: 19px;\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .image1{\r\n");
	      out.write("            width: 90px;\r\n");
	      out.write("            display: block;\r\n");
	      out.write("            border-radius: 70%;\r\n");
	      out.write("            margin : 5px 0px 5px 40px;\r\n");
	      out.write("            \r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .btn{\r\n");
	      out.write("            color:white;\r\n");
	      out.write("            background-color:rgb(70, 70, 70);\r\n");
	      out.write("            padding: 15px 30px;\r\n");
	      out.write("            height: 110px;\r\n");
	      out.write("            margin: 10px;\r\n");
	      out.write("            border-radius: 15px;\r\n");
	      out.write("            border: none;\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .btn:active{\r\n");
	      out.write("            transform: scale(1.1);\r\n");
	      out.write("        }\r\n");
	      out.write("        .btn:hover{\r\n");
	      out.write("            background-color:rgba(173, 173, 173, 0.545);\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .command{\r\n");
	      out.write("            text-align: center;\r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("        .cont2{\r\n");
	      out.write("            /* border: 1px solid rgb(70, 70, 70); */\r\n");
	      out.write("            width: 500px;\r\n");
	      out.write("            margin: 11px;\r\n");
	      out.write("            padding: 10px;\r\n");
	      out.write("            box-sizing: border-box;\r\n");
	      out.write("            border-radius: 15px;\r\n");
	      out.write("            text-align: left;\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .id2{\r\n");
	      out.write("            /* border: 1px solid rgb(70, 70, 70); */\r\n");
	      out.write("            color :rgb(113, 113, 113);\r\n");
	      out.write("            border-radius: 15px;\r\n");
	      out.write("            width: 130px;\r\n");
	      out.write("            font-size: 15px;\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .image2{\r\n");
	      out.write("            width: 75px;\r\n");
	      out.write("            border-radius: 70%;          \r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("        /*댓글 입력한 날짜출력 스타일*/\r\n");
	      out.write("        .date1{\r\n");
	      out.write("            border-radius: 15px;\r\n");
	      out.write("            margin: 11px;\r\n");
	      out.write("            padding: 1px;\r\n");
	      out.write("            text-align: right;\r\n");
	      out.write("            color :rgb(113, 113, 113);\r\n");
	      out.write("            font-size: 13px;\r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("        /* 앨범  < > 용 스타일*/\r\n");
	      out.write("        #cont3{\r\n");
	      out.write("            margin-top : 20px;\r\n");
	      out.write("            text-align: center;\r\n");
	      out.write("        }\r\n");
	      out.write("        #cont3_1{\r\n");
	      out.write("            /*border: 1px solid white;*/\r\n");
	      out.write("            width: 900px;\r\n");
	      out.write("            height: 250px;\r\n");
	      out.write("            position: relative;\r\n");
	      out.write("            margin: 15px auto;\r\n");
	      out.write("            overflow: hidden;\r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("        /*슬라이드 애니메이션*/\r\n");
	      out.write("        #slds{\r\n");
	      out.write("        	transition: margin 0.8s;\r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("        li{\r\n");
	      out.write("            list-style-type: none;\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .clides li:not(:last-child){\r\n");
	      out.write("            float: left;\r\n");
	      out.write("            margin-right: 25px;\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .clides{\r\n");
	      out.write("            position: absolute;\r\n");
	      out.write("            left: 0;\r\n");
	      out.write("            top: 0;\r\n");
	      out.write("            width: 2500px; /* 슬라이드할 사진과 마진 총 넓이 */\r\n");
	      out.write("         }\r\n");
	      out.write("\r\n");
	      out.write("         .clides li{\r\n");
	      out.write("            float: left;\r\n");
	      out.write("            margin-right: 25px;\r\n");
	      out.write("            }\r\n");
	      out.write("            \r\n");
	      out.write("        /* < > 화살표 */    \r\n");
	      out.write("        .point{\r\n");
	      out.write("            border: 1px solid rgb(98, 98, 98);\r\n");
	      out.write("            background-color: transparent;\r\n");
	      out.write("            border-radius: 70%;\r\n");
	      out.write("            width : 30px;\r\n");
	      out.write("            height: 31px;\r\n");
	      out.write("            margin : 10px;\r\n");
	      out.write("            padding: 0px 3px;\r\n");
	      out.write("            padding-bottom: 3px;\r\n");
	      out.write("            font-size: 20px;\r\n");
	      out.write("            display: inline-block;\r\n");
	      out.write("            font-weight: 200;\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .point:hover{\r\n");
	      out.write("            background-color: rgba(128, 128, 128, 0.652);\r\n");
	      out.write("            cursor: pointer;\r\n");
	      out.write("        }\r\n");
	      out.write("\r\n");
	      out.write("        .image{\r\n");
	      out.write("            width: 190px;\r\n");
	      out.write("        }\r\n");
	      out.write("        \r\n");
	      out.write("        .marLeft{\r\n");
	      out.write("        	margin-left: -885px;\r\n");
	      out.write("        }\r\n");
	      out.write("    </style>\r\n");
	      out.write("</head>\r\n");
	      out.write("<body  onscroll=\"headerbarToggle()\">\r\n");
	      out.write("    <header id =\"menu\" >\r\n");
	      out.write("        <span style=\"font-size: 34px; font-weight: 600; cursor: pointer;\">JV Music</span>\r\n");
	      out.write("        <div class=\"menu-box\">\r\n");
	      out.write("            <span class=\"main main_1\" >홈</span>\r\n");
	      out.write("            <span class=\"main main_2\" >인기차트</span>\r\n");
	      out.write("            <span class=\"main main_3\" >보관함</span>\r\n");
	      out.write("            <div class = \"main-box main_4\">\r\n");
	      out.write("                <input class=\"search-txt\" type=\"text\" placeholder=\"검색\">\r\n");
	      out.write("                <button class=\"search-btn\" type=\"submit\">검색</button>\r\n");
	      out.write("            </div>\r\n");
	      out.write("        </div>\r\n");
	      out.write("        <img class=\"menu-img\" src=\"http://blog.tofte-it.dk/wp-content/uploads/2018/12/profile-picture.png\">\r\n");
	      out.write("    </header>\r\n");
	      out.write("    <div id = \"home\">\r\n");
	      out.write("        <div id = \"cont\" class = \"contain\">\r\n");
	      out.write("            <div class = \"text1\">\r\n");
	      out.write("                <h1>아이유(IU)</h1>\r\n");
	      out.write("                <p>아이유는 대한민국의 가수이자 배우이다. 배우로 활동할 때는 본명을 사용한다. \r\n");
	      out.write("                <br>'아이유'라는 예명은 'I'와 'You'를 합친 합성어로 '너와 내가 음악으로 하나가 된다.'라는 의미이다.</p>\r\n");
	      out.write("                <div> <a target=\"_blank\" href=\"https://namu.wiki/w/%EC%95%84%EC%9D%B4%EC%9C%A0\">출처:namuwiki</a></div>\r\n");
	      out.write("            </div>\r\n");
	      out.write("        </div>\r\n");
	      out.write("        <div id =\"cont1_1\">\r\n");
	      out.write("            <h2 style=\"text-align: center; margin: 13px;\">음악</h2>\r\n");
	      out.write("            ");
	 	    
	            AlbumDAO albumDAO = new AlbumDAO();
	        	String num = request.getParameter("a.ALBUM_NUM");
	        	System.out.println("num : "+num);
	    	    List<AlbumVO> Albumlist = albumDAO.listAlbum(); 
	            for(int j=0; j<Albumlist.size(); j++) {
	            	AlbumVO vo = Albumlist.get(j);
	    	    	
	            	String alNum = vo.getAlbum_num();
	    	    	String cover = vo.getAlbum_cover();
	    			String alname = vo.getAlbum_name();
	    			String artist = vo.getArtist();
	            	
	    			String music_name = vo.getMusic_name();
	    			String music_link = vo.getMusic_link();
	            	
	      out.write("\r\n");
	      out.write("            \r\n");
	      out.write("            <div id = \"cont1\">\r\n");
	      out.write("                <div class = \"box1\">\r\n");
	      out.write("                    <img class=\"img1\" src=\"");
	      out.print( cover);
	      out.write("\">\r\n");
	      out.write("                </div>\r\n");
	      out.write("                <div class = \"box1 text2\"><a href=\"");
	      out.print( music_link );
	      out.write("\"><strong>");
	      out.print( music_name );
	      out.write("</strong></a></div>\r\n");
	      out.write("                <div class = \"box1 text2\" style = \"color:rgb(192, 192, 192);\">");
	      out.print( artist );
	      out.write("</div>\r\n");
	      out.write("                <div class = \"box1 text2\"><a style = \"color:rgb(192, 192, 192);\" href=\"/javafood_team/Album.jsp?a.ALBUM_NUM=");
	      out.print( alNum );
	      out.write('"');
	      out.write('>');
	      out.print( alname );
	      out.write("</a></div>\r\n");
	      out.write("            </div>\r\n");
	      out.write("            <hr>\r\n");
	      out.write("            ");
	} 
	      out.write("\r\n");
	      out.write("        </div>\r\n");
	      out.write("        <div id = \"cont3\">\r\n");
	      out.write("                <p class=\"point prev\">&lang;</p>\r\n");
	      out.write("            <h2 style=\"text-align: center; margin: 0px; display: inline;\">앨범</h2>\r\n");
	      out.write("                <p class=\"point next\">&rang;</p>\r\n");
	      out.write("            <div id=\"cont3_1\">\r\n");
	      out.write("                <ul id = \"slds\" class=\"clides\">\r\n");
	      out.write("                ");
	 for(int h=0; h<Albumlist.size(); h++){ 
	                	AlbumVO vo = Albumlist.get(h);
	                	
	                	String alNum = vo.getAlbum_num();
	        	    	String cover = vo.getAlbum_cover();
	        			String alname = vo.getAlbum_name();

	                
	      out.write("\r\n");
	      out.write("                    <li>\r\n");
	      out.write("                        <a href=\"/javafood_team/Album.jsp?a.ALBUM_NUM=");
	      out.print( alNum );
	      out.write("\"><img  class=\"image\" src=\"");
	      out.print( cover);
	      out.write("\"></a>\r\n");
	      out.write("                        <br>\r\n");
	      out.write("                        <a style = \"font-size:14px;\" href=\"/javafood_team/Album.jsp?a.ALBUM_NUM=");
	      out.print( alNum );
	      out.write("\"><span><strong>");
	      out.print( alname );
	      out.write("</strong></span></a>\r\n");
	      out.write("                    </li>\r\n");
	      out.write("                    ");
	} 
	      out.write("\r\n");
	      out.write("                </ul>\r\n");
	      out.write("            </div>\r\n");
	      out.write("        </div>\r\n");
	      out.write("        <div>\r\n");
	      out.write("        	<br>\r\n");
	      out.write("            <h2 style=\"text-align: center; margin: 0px;\">댓글</h2>\r\n");
	      out.write("            <form name=\"frmComment\">\r\n");
	      out.write("                <div class=\"comment\">\r\n");
	      out.write("                    <div class=\"text2\">\r\n");
	      out.write("                        <img class=\"image1\" src=\"http://blog.tofte-it.dk/wp-content/uploads/2018/12/profile-picture.png\">\r\n");
	      out.write("                        <input class=\"input1\" type=\"text\" name=\"id\" placeholder=\" ID를 입력해주세요\">\r\n");
	      out.write("                    </div>\r\n");
	      out.write("                    <div class=\"text2\">\r\n");
	      out.write("                        <textarea name=\"cont\" placeholder=\"*게시물의 저작권 등 분쟁, 개인정보 노출로 인한 책임은 작성자 또는 게시자에게 있음을 유의해 주세요.\"></textarea>\r\n");
	      out.write("                    </div>\r\n");
	      out.write("                    <div class=\"text2\">\r\n");
	      out.write("                        <button class=\"btn\" type=\"button\" onclick=\"fn_sendComment()\"> 등록 </button>\r\n");
	      out.write("                    </div>\r\n");
	      out.write("                    <input type =\"hidden\" name=\"command\" value=\"addcomment\">\r\n");
	      out.write("                </div>\r\n");
	      out.write("            </form>\r\n");
	      out.write("            </div>\r\n");
	      out.write("            <div class=\"command\">\r\n");
	      out.write("            <hr>\r\n");
	      out.write("                ");
	 for(int i= 0; i<list.size(); i++) {
		    	    	  CommentVO vo = list.get(i);
		    	    	  
		    	    	  String id = vo.getComment_id();
		    	    	  String cont = vo.getComment_cont();
		    	    	  Date date = vo.getComment_Date(); 
	      out.write("\r\n");
	      out.write("                <div class=\"comment\">\r\n");
	      out.write("                        <div class=\"text2 cont2_1\">\r\n");
	      out.write("                            <img class=\"image2\" src=\"http://blog.tofte-it.dk/wp-content/uploads/2018/12/profile-picture.png\">\r\n");
	      out.write("                            <div class=\"id2\">");
	      out.print( id );
	      out.write("</div>\r\n");
	      out.write("                        </div>\r\n");
	      out.write("                        <div class=\"text2\">\r\n");
	      out.write("                            <div class=\"cont2\">");
	      out.print( cont );
	      out.write("</div>\r\n");
	      out.write("                            <div class=\"date1\">");
	      out.print( date );
	      out.write("</div>\r\n");
	      out.write("                        </div>\r\n");
	      out.write("                        <div class=\"text2\">\r\n");
	      out.write("                            <a href=\"/javafood_team/artistcomment?command=delcommnet&id=");
	      out.print( id);
	      out.write("\"><button class='btn' type='button'> 삭제 </button></a>\r\n");
	      out.write("                        </div>\r\n");
	      out.write("                </div> ");
	 } 
	      out.write("\r\n");
	      out.write("                \r\n");
	      out.write("                \r\n");
	      out.write("            </div>\r\n");
	      out.write("        </div>\r\n");
	      out.write("\r\n");
	      out.write("\r\n");
	      out.write("</body>\r\n");
	      out.write("</html>");
		
	}

}
