package My_Page;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class tts
 */
@WebServlet("/tts")
public class tts extends HttpServlet {
	private static final long serialVersionUID = 1L;

	protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		response.getWriter().print("<!DOCTYPE html>\r\n"
				+ "<html lang=\"en\">\r\n"
				+ "<head>\r\n"
				+ "    <meta charset=\"UTF-8\">\r\n"
				+ "    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n"
				+ "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n"
				+ "    <title>Document</title>\r\n"
				+ "    <style>\r\n"
				+ "         @charset \"UTF-8\";\r\n"
				+ " @import url(https://fonts.googleapis.com/css?family=Open+Sans:300,400,700);\r\n"
				+ " \r\n"
				+ " body {\r\n"
				+ "   font-family: 'Open Sans', sans-serif;\r\n"
				+ "   font-weight: 300;\r\n"
				+ "   line-height: 1.42em;\r\n"
				+ "   color:#A7A1AE;\r\n"
				+ "   background-color:#1F2739;\r\n"
				+ " }\r\n"
				+ " \r\n"
				+ " h1 {\r\n"
				+ "   font-size:3em; \r\n"
				+ "   font-weight: 300;\r\n"
				+ "   line-height:1em;\r\n"
				+ "   text-align: center;\r\n"
				+ "   color: #4DC3FA;\r\n"
				+ " }\r\n"
				+ " \r\n"
				+ " h2 {\r\n"
				+ "   font-size:1em; \r\n"
				+ "   font-weight: 300;\r\n"
				+ "   text-align: center;\r\n"
				+ "   display: block;\r\n"
				+ "   line-height:1em;\r\n"
				+ "   padding-bottom: 2em;\r\n"
				+ "   color: #FB667A;\r\n"
				+ " }\r\n"
				+ " \r\n"
				+ " h2 a {\r\n"
				+ "   font-weight: 700;\r\n"
				+ "   text-transform: uppercase;\r\n"
				+ "   color: #FB667A;\r\n"
				+ "   text-decoration: none;\r\n"
				+ " }\r\n"
				+ " \r\n"
				+ " .blue { color: #185875; }\r\n"
				+ " .yellow { color: #FFF842; }\r\n"
				+ " \r\n"
				+ " .container th h1 {\r\n"
				+ "     font-weight: bold;\r\n"
				+ "     font-size: 1em;\r\n"
				+ "   text-align: left;\r\n"
				+ "   color: #185875;\r\n"
				+ " }\r\n"
				+ " \r\n"
				+ " .container td {\r\n"
				+ "     font-weight: normal;\r\n"
				+ "     font-size: 1em;\r\n"
				+ "   -webkit-box-shadow: 0 2px 2px -2px #0E1119;\r\n"
				+ "      -moz-box-shadow: 0 2px 2px -2px #0E1119;\r\n"
				+ "           box-shadow: 0 2px 2px -2px #0E1119;\r\n"
				+ " }\r\n"
				+ " \r\n"
				+ " .container {\r\n"
				+ "     text-align: left;\r\n"
				+ "     overflow: hidden;\r\n"
				+ "     width: 80%;\r\n"
				+ "     margin: 0 auto;\r\n"
				+ "   display: table;\r\n"
				+ "   padding: 0 0 8em 0;\r\n"
				+ " }\r\n"
				+ " \r\n"
				+ " .container td, .container th {\r\n"
				+ "     padding-bottom: 2%;\r\n"
				+ "     padding-top: 2%;\r\n"
				+ "   padding-left:2%;  \r\n"
				+ " }\r\n"
				+ " \r\n"
				+ " /* Background-color of the odd rows */\r\n"
				+ " .container tr:nth-child(odd) {\r\n"
				+ "     background-color: #323C50;\r\n"
				+ " }\r\n"
				+ " \r\n"
				+ " /* Background-color of the even rows */\r\n"
				+ " .container tr:nth-child(even) {\r\n"
				+ "     background-color: #2C3446;\r\n"
				+ " }\r\n"
				+ " \r\n"
				+ " .container th {\r\n"
				+ "     background-color: #1F2739;\r\n"
				+ " }\r\n"
				+ " \r\n"
				+ " .container td:first-child { color: #FB667A; }\r\n"
				+ " \r\n"
				+ " .container tr:hover {\r\n"
				+ "    background-color: #464A52;\r\n"
				+ " -webkit-box-shadow: 0 6px 6px -6px #0E1119;\r\n"
				+ "      -moz-box-shadow: 0 6px 6px -6px #0E1119;\r\n"
				+ "           box-shadow: 0 6px 6px -6px #0E1119;\r\n"
				+ " }\r\n"
				+ " \r\n"
				+ " .container td:hover {\r\n"
				+ "   background-color: #FFF842;\r\n"
				+ "   color: #403E10;\r\n"
				+ "   font-weight: bold;\r\n"
				+ "   \r\n"
				+ "   box-shadow: #7F7C21 -1px 1px, #7F7C21 -2px 2px, #7F7C21 -3px 3px, #7F7C21 -4px 4px, #7F7C21 -5px 5px, #7F7C21 -6px 6px;\r\n"
				+ "   transform: translate3d(6px, -6px, 0);\r\n"
				+ "   \r\n"
				+ "   transition-delay: 0s;\r\n"
				+ "     transition-duration: 0.4s;\r\n"
				+ "     transition-property: all;\r\n"
				+ "   transition-timing-function: line;\r\n"
				+ " }\r\n"
				+ " \r\n"
				+ " @media (max-width: 800px) {\r\n"
				+ " .container td:nth-child(4),\r\n"
				+ " .container th:nth-child(4) { display: none; }\r\n"
				+ " }\r\n"
				+ "    </style>\r\n"
				+ "</head>\r\n"
				+ "<body>\r\n"
				+ "    <h1><span class=\"blue\">&lt;</span>Table<span class=\"blue\">&gt;</span> <span class=\"yellow\">Responsive</pan></h1>\r\n"
				+ "        <h2>Created with love by <a href=\"https://github.com/pablorgarcia\" target=\"_blank\">Pablo García</a></h2>\r\n"
				+ "        \r\n"
				+ "        <table class=\"container\">\r\n"
				+ "          <thead>\r\n"
				+ "            <tr>\r\n"
				+ "              <th><h1>123</h1></th>\r\n"
				+ "              <th><h1>123</h1></th>\r\n"
				+ "              <th><h1>123</h1></th>\r\n"
				+ "              <th><h1>123</h1></th>\r\n"
				+ "            </tr>\r\n"
				+ "          </thead>\r\n"
				+ "          <tbody>\r\n"
				+ "            <tr>\r\n"
				+ "              <td>123</td>\r\n"
				+ "              <td>123</td>\r\n"
				+ "              <td>123</td>\r\n"
				+ "              <td>123:123:123</td>\r\n"
				+ "            </tr>\r\n"
				+ "            <tr>\r\n"
				+ "              <td>123</td>\r\n"
				+ "              <td>123</td>\r\n"
				+ "              <td>123</td>\r\n"
				+ "              <td>123</td>\r\n"
				+ "            </tr>\r\n"
				+ "            <tr>\r\n"
				+ "              <td>Amazon</td>\r\n"
				+ "              <td>4162</td>\r\n"
				+ "              <td>5327</td>\r\n"
				+ "              <td>00:24:34</td>\r\n"
				+ "            </tr>\r\n"
				+ "            <tr>\r\n"
				+ "              <td>LinkedIn</td>\r\n"
				+ "              <td>3654</td>\r\n"
				+ "              <td>2961</td>\r\n"
				+ "              <td>00:12:10</td>\r\n"
				+ "            </tr>\r\n"
				+ "            <tr>\r\n"
				+ "              <td>CodePen</td>\r\n"
				+ "              <td>2002</td>\r\n"
				+ "              <td>4135</td>\r\n"
				+ "              <td>00:46:19</td>\r\n"
				+ "            </tr>\r\n"
				+ "            <tr>\r\n"
				+ "              <td>GitHub</td>\r\n"
				+ "              <td>4623</td>\r\n"
				+ "              <td>3486</td>\r\n"
				+ "              <td>00:31:52</td>\r\n"
				+ "            </tr>\r\n"
				+ "          </tbody>\r\n"
				+ "        </table>\r\n"
				+ "</body>\r\n"
				+ "</html>");
	}

}
